### PR TITLE
add test for off-port git remote

### PR DESCRIPTION
**Pull request by michaelshobbs**
Adds test for off-port git remotes and associated test-env configuration.
Rebased from master. Tests were broken at the point where you had branched.

### CODE REVIEW

**Comment by michaelshobbs** [comment]
Tests are running here: https://circleci.com/gh/progrium/dokku/480

**Comment by michaelshobbs** [comment]
Tests are running here: https://circleci.com/gh/progrium/dokku/482

**Comment by michaelshobbs** [comment]
Rebased from master.

**Comment by littldr** [comment]
Cool! Thank you! :-)

**Pull request merged**
